"use client";

import { useState } from "react";
import ListToolbar, { exportCsv, paginate } from "@/components/ListToolbar";
import type { AccountProfile } from "@/components/AccountsPanel";
import type { SecureDocumentRow } from "@/components/DocumentVault";

export type AuditLogRow={id:string;actor_id:string|null;action:string;entity_type:string;entity_id:string|null;details:Record<string,unknown>;old_data:Record<string,unknown>|null;new_data:Record<string,unknown>|null;source_ip:string|null;user_agent:string|null;created_at:string};
export type SessionActivityRow={id:string;user_id:string;session_identifier:string;source_ip:string|null;user_agent:string|null;first_seen_at:string;last_seen_at:string;revoked_at:string|null};
export type DocumentAccessLogRow={id:string;document_id:string;version_id:string|null;user_id:string|null;action:string;source_ip:string|null;user_agent:string|null;details:Record<string,unknown>;created_at:string};

export default function AuditCenter({logs,sessions,documentAccess,profiles,documents}:{logs:AuditLogRow[];sessions:SessionActivityRow[];documentAccess:DocumentAccessLogRow[];profiles:AccountProfile[];documents:SecureDocumentRow[]}){
  const [view,setView]=useState("changes");const [query,setQuery]=useState("");const [type,setType]=useState("all");const [page,setPage]=useState(1);
  const names=Object.fromEntries(profiles.map(row=>[row.id,row.full_name||row.email||row.id]));const documentNames=Object.fromEntries(documents.map(row=>[row.id,row.title]));
  const types=Array.from(new Set(logs.map(row=>row.entity_type))).sort();
  const filtered=logs.filter(row=>`${row.action} ${row.entity_type} ${row.entity_id||""} ${row.actor_id||""}`.toLowerCase().includes(query.toLowerCase())&&(type==="all"||row.entity_type===type));const paged=paginate(filtered,page,15);
  return <section className="operationsWorkspace auditCenter"><div className="statGrid operationStats"><article><b>{logs.length}</b><span>Changements tracés</span></article><article><b>{sessions.length}</b><span>Sessions observées</span></article><article><b>{documentAccess.length}</b><span>Accès documentaires</span></article><article><b>{sessions.filter(row=>row.revoked_at).length}</b><span>Sessions révoquées</span></article></div><div className="operationNav">{[["changes","Modifications"],["sessions","Connexions"],["documents","Documents"]].map(([id,label])=><button key={id} className={view===id?"active":""} onClick={()=>setView(id)}>{label}</button>)}</div>
    {view==="changes"&&<div className="portalPanel"><h2>Journal d’audit non modifiable</h2><p>Chaque entrée indique l’auteur, l’ancienne valeur, la nouvelle valeur et l’horodatage. Les récits sensibles ne sont pas dupliqués dans le journal.</p><ListToolbar query={query} onQuery={setQuery} status={type} onStatus={setType} options={types.map(value=>({value,label:value}))} count={filtered.length} page={paged.page} pages={paged.pages} onPage={setPage} onExport={()=>exportCsv("audit-aiac.csv",["Action","Entité","Identifiant","Acteur","Ancienne valeur","Nouvelle valeur","Date"],filtered.map(row=>[row.action,row.entity_type,row.entity_id,names[row.actor_id||""]||row.actor_id,JSON.stringify(row.old_data),JSON.stringify(row.new_data),row.created_at]))} placeholder="Action, entité, identifiant ou acteur"/>{paged.items.map(log=><details className="workflowCard" key={log.id}><summary><span><b>{log.action}</b><small>{log.entity_type} · {log.entity_id||"—"} · {names[log.actor_id||""]||log.actor_id||"système"}</small></span><time>{new Date(log.created_at).toLocaleString("fr-FR")}</time></summary><div className="workflowBody auditDiff"><div><h3>Avant</h3><pre>{JSON.stringify(log.old_data,null,2)||"—"}</pre></div><div><h3>Après</h3><pre>{JSON.stringify(log.new_data,null,2)||"—"}</pre></div></div></details>)}</div>}
    {view==="sessions"&&<div className="portalPanel"><h2>Historique des connexions et révocations</h2>{sessions.map(row=><div className="listRow" key={row.id}><div><b>{names[row.user_id]||row.user_id}</b><small>{row.source_ip||"IP non disponible"} · {row.user_agent?.slice(0,100)||"Appareil non renseigné"}</small></div><span>{row.revoked_at?`Révoquée ${new Date(row.revoked_at).toLocaleString("fr-FR")}`:`Vue ${new Date(row.last_seen_at).toLocaleString("fr-FR")}`}</span></div>)}</div>}
    {view==="documents"&&<div className="portalPanel"><h2>Consultations et téléchargements sensibles</h2>{documentAccess.map(row=><div className="listRow" key={row.id}><div><b>{row.action} · {documentNames[row.document_id]||row.document_id}</b><small>{names[row.user_id||""]||row.user_id||"système"} · {row.source_ip||"IP non disponible"}</small></div><time>{new Date(row.created_at).toLocaleString("fr-FR")}</time></div>)}</div>}
  </section>;
}
