"use client";

import { useMemo } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";

const labels:Record<string,string>={member:"Membre",beneficiary:"Bénéficiaire",volunteer:"Bénévole",staff:"Personnel AIAC",manager:"Responsable d’organe",partner:"Partenaire",admin:"Administrateur",super_admin:"Super-administrateur"};
const links=[["accueil","Tableau de bord"],["reunions","Réunions et agenda"],["demandes","Mes demandes"],["messages","Messagerie"],["notifications","Notifications"],["annonces","Annonces"],["profil","Mon profil"],["poste","Mon poste"],["terrain","Cycle des programmes"],["operations","Demandes et interventions"],["institution","Gouvernance et membres"],["documents","Documents sécurisés"],["contenus","Publications du site"],["administration","Comptes et accès"],["data-control","Contrôle des données"],["audit","Journal d’audit"]];
export default function InstitutionalSidebar({profile,active}:{profile:{full_name:string|null;email:string|null;role:string};active:string}){const supabase=useMemo(()=>createClient(),[]);const router=useRouter();const isAdmin=['admin','super_admin'].includes(profile.role),isSuper=profile.role==='super_admin',isStaff=['staff','manager','admin','super_admin'].includes(profile.role);function go(id:string){if(id==='accueil')router.push('/espace');else if(id==='poste')router.push('/espace/poste');else if(id==='terrain')router.push('/espace/terrain');else router.push(`/espace?tab=${encodeURIComponent(id)}`);}async function logout(){await supabase.auth.signOut();router.push('/connexion');router.refresh();}return <aside className="portalSidebar"><a href="/nouveau-site/index.html" className="portalBrand"><img src="/aiac-logo.bmp" alt="AIAC"/><span><b>AIAC</b><small>Site public</small></span></a><div className="portalIdentity"><span aria-hidden="true">{(profile.full_name||profile.email||'A').charAt(0).toUpperCase()}</span><div><b>{profile.full_name||'Membre AIAC'}</b><small>{labels[profile.role]||profile.role}</small></div></div><nav>{links.filter(([id])=>{if(['operations','institution','documents','contenus'].includes(id))return isStaff;if(id==='administration')return isAdmin;if(['data-control','audit'].includes(id))return isSuper;return true;}).map(([id,label])=><button type="button" key={id} className={id===active?'active':''} onClick={()=>go(id)}><span>{label}</span></button>)}</nav><a className="publicSiteLink" href="/nouveau-site/index.html">Voir le site public</a><button className="logout" onClick={()=>void logout()}>Se déconnecter</button></aside>}
