"use client";

import { ChangeEvent,useEffect,useMemo,useState } from "react";
import JSZip from "jszip";
import { createClient } from "@/lib/supabase/client";

type Pending={name:string;blob:Blob;type:string;size:number};
const mime:Record<string,string>={pdf:"application/pdf",docx:"application/vnd.openxmlformats-officedocument.wordprocessingml.document",doc:"application/msword",xlsx:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",xls:"application/vnd.ms-excel",pptx:"application/vnd.openxmlformats-officedocument.presentationml.presentation",ppt:"application/vnd.ms-powerpoint",txt:"text/plain",csv:"text/csv",png:"image/png",jpg:"image/jpeg",jpeg:"image/jpeg",webp:"image/webp"};
function baseName(path:string){return path.split('/').filter(Boolean).pop()||path;}
function safeName(name:string){return name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9._-]/g,'-');}
function typeFor(name:string,provided=''){return provided||mime[name.split('.').pop()?.toLowerCase()||'']||'application/octet-stream';}
async function sha(blob:Blob){const b=await blob.arrayBuffer();return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',b))).map(x=>x.toString(16).padStart(2,'0')).join('');}
export default function InstitutionalLibraryImporter({onDone}:{onDone?:()=>void}){const supabase=useMemo(()=>createClient(),[]);const[allowed,setAllowed]=useState(false);const[items,setItems]=useState<Pending[]>([]);const[busy,setBusy]=useState(false);const[progress,setProgress]=useState('');const[notice,setNotice]=useState('');useEffect(()=>{void(async()=>{const{data:{user}}=await supabase.auth.getUser();if(!user)return;const{data}=await supabase.from('profiles').select('role').eq('id',user.id).single();setAllowed(data?.role==='super_admin');})();},[supabase]);if(!allowed)return null;
 async function choose(e:ChangeEvent<HTMLInputElement>){setNotice('');const selected=Array.from(e.target.files||[]);const out:Pending[]=[];for(const f of selected){if(f.name.toLowerCase().endsWith('.zip')){try{const zip=await JSZip.loadAsync(f);for(const entry of Object.values(zip.files)){if(entry.dir||entry.name.includes('__MACOSX/')||baseName(entry.name).startsWith('.'))continue;const blob=await entry.async('blob');if(!blob.size)continue;const name=baseName(entry.name);out.push({name,blob,type:typeFor(name),size:blob.size});}}catch(err){setNotice(`ZIP illisible : ${f.name}`);}}else out.push({name:f.name,blob:f,type:typeFor(f.name,f.type),size:f.size});}const seen=new Set<string>();setItems(out.filter(x=>{const k=`${x.name}:${x.size}`;if(seen.has(k))return false;seen.add(k);return true;}));}
 async function previewDocx(documentId:string,blob:Blob){try{const mammoth=await import('mammoth');const result=await mammoth.convertToHtml({arrayBuffer:await blob.arrayBuffer()});if(result.value)await supabase.rpc('set_institutional_document_preview',{target_document_id:documentId,target_html:`<article class="aiac-doc">${result.value}</article>`});}catch{/* L'original reste consultable/téléchargeable selon les droits. */}}
 async function sync(){if(!items.length)return;setBusy(true);setNotice('');let ok=0,created=0,failed=0;const{data:{user}}=await supabase.auth.getUser();if(!user){setBusy(false);return;}const{data:folder}=await supabase.from('document_folders').select('id').eq('name','Référentiel institutionnel').is('parent_id',null).maybeSingle();for(let i=0;i<items.length;i++){const item=items[i];setProgress(`${i+1}/${items.length} · ${item.name}`);try{const{data:existing}=await supabase.from('documents').select('id,current_version,file_name').eq('institutional_library',true).eq('file_name',item.name).limit(1).maybeSingle();const path=`institutional-library/${crypto.randomUUID()}-${safeName(item.name)}`;const up=await supabase.storage.from('aiac-documents').upload(path,item.blob,{contentType:item.type,upsert:false});if(up.error)throw up.error;let id:string;let version=1;if(existing){id=existing.id;const{data:last}=await supabase.from('document_versions').select('version_number').eq('document_id',id).order('version_number',{ascending:false}).limit(1).maybeSingle();version=Number(last?.version_number||0)+1;const{error}=await supabase.from('documents').update({file_url:path,mime_type:item.type,size_bytes:item.size,document_status:'approved'}).eq('id',id);if(error)throw error;}else{const{data:d,error}=await supabase.from('documents').insert({owner_id:user.id,title:item.name.replace(/\.[^.]+$/,''),file_url:path,file_name:item.name,mime_type:item.type,size_bytes:item.size,visibility:'explicit',folder_id:folder?.id||null,classification:'internal',document_status:'approved',institutional_library:true,download_policy:'standard',secure_view_only:false,source_reference:`AIAC-BULK:${item.name}`}).select('id').single();if(error||!d)throw error||new Error('Création impossible');id=d.id;created++;}const{error:ve}=await supabase.from('document_versions').insert({document_id:id,version_number:version,storage_path:path,file_name:item.name,mime_type:item.type,size_bytes:item.size,checksum_sha256:await sha(item.blob),change_note:existing?'Synchronisation de la bibliothèque AIAC':'Import institutionnel initial',created_by:user.id});if(ve)throw ve;if(item.name.toLowerCase().endsWith('.docx'))await previewDocx(id,item.blob);ok++;}catch(err){failed++;console.error(err);}}setBusy(false);setProgress('');setNotice(`${ok} fichier(s) synchronisé(s)${created?` · ${created} nouveau(x) document(s) à classer`:''}${failed?` · ${failed} échec(s)`:''}.`);setItems([]);onDone?.();}
 return <details className="pwNested"><summary>Super-administration · Importer / synchroniser la bibliothèque AIAC</summary><div className="pwInset"><p>Sélectionnez plusieurs fichiers ou un/plusieurs ZIP. Les noms déjà catalogués sont reliés automatiquement à leur fiche et conservent leurs droits par poste.</p><input type="file" multiple accept=".zip,.pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx,.txt,.csv,.png,.jpg,.jpeg,.webp" onChange={e=>void choose(e)} disabled={busy}/>{items.length>0&&<><p><b>{items.length}</b> fichier(s) prêt(s) à synchroniser.</p><div className="pwScroll" style={{maxHeight:220}}><ul>{items.slice(0,250).map((x,i)=><li key={`${x.name}-${i}`}>{x.name} · {(x.size/1024).toFixed(0)} Ko</li>)}</ul></div><button onClick={()=>void sync()} disabled={busy}>{busy?'Synchronisation…':'Importer dans le coffre'}</button></>}{progress&&<p>{progress}</p>}{notice&&<p className="pwWarning">{notice}</p>}</div></details>}
