"use client";

import {useCallback,useEffect,useMemo,useState} from "react";
import type {FormEvent} from "react";
import {useSearchParams} from "next/navigation";
import {createClient} from "@/lib/supabase/client";

type Meeting={id:string;code:string;title:string;status:string;starts_at:string;ends_at:string;organizer_id:string;venue:string|null;modality:string;meeting_url:string|null};
type Participant={meeting_id:string;user_id:string;participant_role:string;response_status:string};
type Directory={id:string;full_name:string;email:string|null;role:string;organization:string|null};
type PersonalTask={id:string;user_id:string;title:string;description:string|null;starts_at:string;ends_at:string|null;status:string;notify_email:boolean};
type AssignedTask={id:string;title:string;description:string|null;due_at:string|null;status:string;assigned_to:string|null;created_by:string};
type CalendarItem={id:string;kind:"meeting"|"personal"|"assigned";title:string;at:string;status:string;href?:string};

function cloneDate(value:Date){return new Date(value.getTime());}
function localInputToIso(value:string){return value?new Date(`${value}:00+01:00`).toISOString():null;}
function format(value:string){return new Date(value).toLocaleString("fr-FR",{dateStyle:"medium",timeStyle:"short",timeZone:"Africa/Douala"});}
function dayKey(value:Date|string){const date=value instanceof Date?value:new Date(value);return date.toLocaleDateString("en-CA",{timeZone:"Africa/Douala"});}
function startOfWeek(date:Date){const d=cloneDate(date);const dow=(d.getDay()+6)%7;d.setHours(12,0,0,0);d.setDate(d.getDate()-dow);return d;}
function monthGrid(anchor:Date){const first=new Date(anchor.getFullYear(),anchor.getMonth(),1,12);const start=startOfWeek(first);return Array.from({length:42},(_,i)=>{const d=cloneDate(start);d.setDate(start.getDate()+i);return d;});}
function weekGrid(anchor:Date){const start=startOfWeek(anchor);return Array.from({length:7},(_,i)=>{const d=cloneDate(start);d.setDate(start.getDate()+i);return d;});}

export default function MeetingAgendaEnhancements({profileId}:{profileId:string}){
 const params=useSearchParams();const visible=params.get("tab")==="reunions";
 const supabase=useMemo(()=>createClient(),[]);
 const [meetings,setMeetings]=useState<Meeting[]>([]);const[participants,setParticipants]=useState<Participant[]>([]);const[directory,setDirectory]=useState<Directory[]>([]);
 const[hidden,setHidden]=useState<string[]>([]);const[personal,setPersonal]=useState<PersonalTask[]>([]);const[assigned,setAssigned]=useState<AssignedTask[]>([]);
 const[mode,setMode]=useState<"month"|"week">("month");const[anchor,setAnchor]=useState(new Date());const[notice,setNotice]=useState("");const[busy,setBusy]=useState("");
 const names=useMemo(()=>new Map<string,Directory>(directory.map(p=>[p.id,p] as [string,Directory])),[directory]);

 const load=useCallback(async()=>{
   const [{data:m},{data:p},{data:d},{data:h},{data:pt},{data:at}]=await Promise.all([
     supabase.from("meetings").select("id,code,title,status,starts_at,ends_at,organizer_id,venue,modality,meeting_url").order("starts_at"),
     supabase.from("meeting_participants").select("meeting_id,user_id,participant_role,response_status"),
     supabase.rpc("list_meeting_directory"),
     supabase.from("meeting_user_visibility").select("meeting_id").eq("user_id",profileId),
     supabase.from("personal_agenda_tasks").select("*").eq("user_id",profileId).order("starts_at"),
     supabase.from("tasks").select("id,title,description,due_at,status,assigned_to,created_by").or(`assigned_to.eq.${profileId},created_by.eq.${profileId}`).not("due_at","is",null).order("due_at"),
   ]);
   setMeetings((m||[]) as Meeting[]);setParticipants((p||[]) as Participant[]);setDirectory((d||[]) as Directory[]);setHidden((h||[]).map((x:any)=>x.meeting_id));setPersonal((pt||[]) as PersonalTask[]);setAssigned((at||[]) as AssignedTask[]);
 },[profileId,supabase]);

 const applyHiddenToExistingHistory=useCallback(()=>{
   if(typeof document==="undefined")return;
   document.querySelectorAll<HTMLElement>("article[id^='meeting-']").forEach(node=>{const id=node.id.replace(/^meeting-/,"");node.style.display=hidden.includes(id)?"none":"";});
 },[hidden]);

 useEffect(()=>{if(!visible)return;void load();const timer=window.setInterval(()=>void load(),60000);const observer=new MutationObserver(()=>applyHiddenToExistingHistory());observer.observe(document.body,{childList:true,subtree:true});const channel=supabase.channel(`agenda-enhancements:${profileId}`).on("postgres_changes",{event:"*",schema:"public",table:"meetings"},()=>void load()).on("postgres_changes",{event:"*",schema:"public",table:"personal_agenda_tasks",filter:`user_id=eq.${profileId}`},()=>void load()).on("postgres_changes",{event:"*",schema:"public",table:"meeting_user_visibility",filter:`user_id=eq.${profileId}`},()=>void load()).subscribe();return()=>{window.clearInterval(timer);observer.disconnect();void supabase.removeChannel(channel);};},[applyHiddenToExistingHistory,load,profileId,supabase,visible]);
 useEffect(()=>{if(visible)window.setTimeout(applyHiddenToExistingHistory,250);},[applyHiddenToExistingHistory,visible]);

 if(!visible)return null;
 const ownMeetings=meetings.filter(m=>participants.some(p=>p.meeting_id===m.id&&p.user_id===profileId)||m.organizer_id===profileId);
 const shownMeetings=ownMeetings.filter(m=>!hidden.includes(m.id));const hiddenMeetings=ownMeetings.filter(m=>hidden.includes(m.id));
 const items:CalendarItem[]=[...shownMeetings.map(m=>({id:m.id,kind:"meeting" as const,title:m.title,at:m.starts_at,status:m.status,href:`/espace?tab=reunions&meeting=${m.id}`})),...personal.filter(t=>t.status!=="cancelled").map(t=>({id:t.id,kind:"personal" as const,title:t.title,at:t.starts_at,status:t.status})),...assigned.filter(t=>t.due_at).map(t=>({id:t.id,kind:"assigned" as const,title:t.title,at:t.due_at!,status:String(t.status),href:"/espace?tab=operations"}))];
 const days=mode==="month"?monthGrid(anchor):weekGrid(anchor);const label=mode==="month"?anchor.toLocaleDateString("fr-FR",{month:"long",year:"numeric"}):`${days[0].toLocaleDateString("fr-FR",{day:"2-digit",month:"short"})} – ${days[days.length-1].toLocaleDateString("fr-FR",{day:"2-digit",month:"short",year:"numeric"})}`;

 async function toggleHidden(id:string,value:boolean){setBusy(`hide-${id}`);const{error}=await supabase.rpc("set_meeting_hidden",{target_meeting:id,p_hidden:value});if(error)setNotice(error.message);else{setNotice(value?"Réunion masquée de votre historique personnel.":"Réunion réaffichée dans votre historique.");await load();}setBusy("");}
 async function createTask(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy("new-task");const form=event.currentTarget;const fd=new FormData(form);const start=localInputToIso(String(fd.get("starts_at")||""));const end=localInputToIso(String(fd.get("ends_at")||""));if(!start){setNotice("Indiquez l’heure prévue.");setBusy("");return;}const{error}=await supabase.from("personal_agenda_tasks").insert({user_id:profileId,title:String(fd.get("title")||"").trim(),description:String(fd.get("description")||"").trim()||null,starts_at:start,ends_at:end,timezone:"Africa/Douala",notify_email:fd.get("notify_email")==="on"});if(error)setNotice(error.message);else{form.reset();setNotice("Tâche planifiée. Les rappels 30 min, 5 min et heure H sont activés.");await load();}setBusy("");}
 async function taskStatus(task:PersonalTask,status:string){setBusy(`task-${task.id}`);const{error}=await supabase.from("personal_agenda_tasks").update({status,completed_at:status==="completed"?new Date().toISOString():null,updated_at:new Date().toISOString()}).eq("id",task.id).eq("user_id",profileId);if(error)setNotice(error.message);else await load();setBusy("");}
 async function deleteTask(task:PersonalTask){if(!window.confirm(`Supprimer « ${task.title} » ?`))return;setBusy(`task-${task.id}`);const{error}=await supabase.from("personal_agenda_tasks").delete().eq("id",task.id).eq("user_id",profileId);if(error)setNotice(error.message);else await load();setBusy("");}
 async function closeMeeting(m:Meeting){if(!window.confirm(`Mettre fin maintenant à « ${m.title} » ?`))return;setBusy(`close-${m.id}`);const{error}=await supabase.rpc("set_meeting_status",{target_meeting:m.id,target_status:"completed"});if(error)setNotice(error.message);else{setNotice("Réunion terminée et historique mis à jour.");await load();}setBusy("");}
 function move(delta:number){setAnchor(current=>{const d=cloneDate(current);if(mode==="month")d.setMonth(d.getMonth()+delta);else d.setDate(d.getDate()+delta*7);return d;});}

 return <section className="aiacAgendaExtension">
   <style jsx global>{`.aiacAgendaExtension{margin:22px 0;padding:0 2px;color:#172033}.aiacAgendaCard{background:#fff;border:1px solid #dbe3ec;border-radius:16px;padding:18px;margin:16px 0;box-shadow:0 6px 20px #0000000a}.aiacAgendaHeader{display:flex;gap:12px;align-items:center;justify-content:space-between;flex-wrap:wrap}.aiacAgendaHeader h3{margin:0}.aiacAgendaButtons{display:flex;gap:7px;flex-wrap:wrap}.aiacAgendaButtons button{border:1px solid #cbd5e1;background:#fff;padding:8px 11px;border-radius:8px;cursor:pointer}.aiacAgendaButtons button.active{background:#173b63;color:#fff}.aiacCalendar{display:grid;grid-template-columns:repeat(7,minmax(0,1fr));gap:5px;margin-top:14px}.aiacDay{min-height:116px;border:1px solid #e2e8f0;border-radius:10px;padding:7px;background:#fafbfc}.aiacDay.today{border:2px solid #166534}.aiacDay.out{opacity:.55}.aiacDayNum{font-weight:800;font-size:12px}.aiacEvent{display:block;margin-top:5px;padding:5px 6px;border-radius:6px;background:#eef2f7;color:#173b63;text-decoration:none;font-size:11px;line-height:1.25}.aiacEvent.personal{background:#ecfdf5;color:#166534}.aiacEvent.assigned{background:#fff7ed;color:#9a3412}.aiacAgendaForm{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.aiacAgendaForm label{display:grid;gap:5px;font-weight:700}.aiacAgendaForm input,.aiacAgendaForm textarea{padding:9px;border:1px solid #cbd5e1;border-radius:8px}.aiacAgendaForm .wide{grid-column:1/-1}.aiacAgendaForm button,.aiacAgendaPrimary{border:0;border-radius:8px;padding:10px 13px;background:#173b63;color:#fff;font-weight:800;cursor:pointer}.aiacHistoryRow{display:flex;justify-content:space-between;gap:12px;align-items:center;border-top:1px solid #edf0f3;padding:10px 0}.aiacHistoryRow:first-of-type{border-top:0}.aiacHistoryRow small{display:block;color:#64748b;margin-top:3px}.aiacHistoryActions{display:flex;gap:7px;flex-wrap:wrap}.aiacHistoryActions button{padding:7px 9px;border:1px solid #cbd5e1;border-radius:7px;background:white;cursor:pointer}.aiacPersonalRow{display:flex;justify-content:space-between;gap:12px;padding:9px 0;border-top:1px solid #edf0f3}.aiacPersonalRow:first-of-type{border-top:0}@media(max-width:850px){.aiacCalendar{grid-template-columns:1fr}.aiacDay{min-height:auto}.aiacAgendaForm{grid-template-columns:1fr}.aiacAgendaForm .wide{grid-column:auto}}`}</style>
   {notice&&<div className="notice" role="status">{notice}<button onClick={()=>setNotice("")}>×</button></div>}
   <div className="aiacAgendaCard">
     <div className="aiacAgendaHeader"><div><h3>Agenda calendrier</h3><p>Réunions, tâches institutionnelles et tâches personnelles · heure du Cameroun.</p></div><div className="aiacAgendaButtons"><button onClick={()=>move(-1)}>←</button><button onClick={()=>setAnchor(new Date())}>Aujourd’hui</button><button onClick={()=>move(1)}>→</button><button className={mode==="week"?"active":""} onClick={()=>setMode("week")}>Semaine</button><button className={mode==="month"?"active":""} onClick={()=>setMode("month")}>Mois</button></div></div>
     <h4 style={{textTransform:"capitalize"}}>{label}</h4>
     <div className="aiacCalendar">{days.map(day=>{const key=dayKey(day);const list=items.filter(item=>dayKey(item.at)===key).sort((a,b)=>+new Date(a.at)-+new Date(b.at));const today=key===dayKey(new Date());const outside=mode==="month"&&day.getMonth()!==anchor.getMonth();return <div className={`aiacDay ${today?"today":""} ${outside?"out":""}`} key={key}><div className="aiacDayNum">{day.toLocaleDateString("fr-FR",{weekday:"short",day:"2-digit",month:"short"})}</div>{list.slice(0,6).map(item=>item.href?<a className={`aiacEvent ${item.kind}`} href={item.href} key={`${item.kind}-${item.id}`}>{new Date(item.at).toLocaleTimeString("fr-FR",{hour:"2-digit",minute:"2-digit",timeZone:"Africa/Douala"})} · {item.title}</a>:<div className={`aiacEvent ${item.kind}`} key={`${item.kind}-${item.id}`}>{new Date(item.at).toLocaleTimeString("fr-FR",{hour:"2-digit",minute:"2-digit",timeZone:"Africa/Douala"})} · {item.title}</div>)}{list.length>6&&<small>+ {list.length-6} autre(s)</small>}</div>;})}</div>
   </div>
   <div className="aiacAgendaCard"><h3>Planifier une tâche personnelle</h3><p>Vous recevrez automatiquement une notification dans AIAC et, si l’option reste cochée, un e-mail 30 minutes avant, 5 minutes avant et à l’heure prévue.</p><form className="aiacAgendaForm" onSubmit={createTask}><label>Titre<input name="title" minLength={2} maxLength={220} required/></label><label>Début<input name="starts_at" type="datetime-local" required/></label><label>Fin facultative<input name="ends_at" type="datetime-local"/></label><label className="wide">Description<textarea name="description" maxLength={10000}/></label><label className="wide" style={{display:"flex",alignItems:"center",gap:8}}><input name="notify_email" type="checkbox" defaultChecked/> Envoyer aussi les rappels par e-mail</label><div className="wide"><button disabled={busy==="new-task"}>Planifier la tâche</button></div></form>{personal.length>0&&<div style={{marginTop:14}}><h4>Mes tâches planifiées</h4>{personal.slice().sort((a,b)=>+new Date(a.starts_at)-+new Date(b.starts_at)).map(t=><div className="aiacPersonalRow" key={t.id}><div><b>{t.title}</b><small>{format(t.starts_at)} · {t.status}</small></div><div className="aiacHistoryActions">{!['completed','cancelled'].includes(t.status)&&<button onClick={()=>void taskStatus(t,"completed")}>Terminée</button>}{t.status!=="cancelled"&&t.status!=="completed"&&<button onClick={()=>void taskStatus(t,"cancelled")}>Annuler</button>}<button onClick={()=>void deleteTask(t)}>Supprimer</button></div></div>)}</div>}</div>
   <div className="aiacAgendaCard"><h3>Historique personnel des réunions</h3><p>Masquer ne supprime pas la réunion institutionnelle : cela la cache seulement de votre propre historique. Vous pouvez la réafficher à tout moment.</p>{shownMeetings.slice().sort((a,b)=>+new Date(b.starts_at)-+new Date(a.starts_at)).map(m=>{const org=names.get(m.organizer_id);return <div className="aiacHistoryRow" key={m.id}><div><b>{m.title}</b><small>{m.code} · {format(m.starts_at)} · {m.status}</small><small>Organisateur : {org?.full_name||"Membre AIAC"}{org?.email?` · ${org.email}`:""}</small></div><div className="aiacHistoryActions">{m.organizer_id===profileId&&m.status==="in_progress"&&<button disabled={busy===`close-${m.id}`} onClick={()=>void closeMeeting(m)}>Terminer maintenant</button>}<button disabled={busy===`hide-${m.id}`} onClick={()=>void toggleHidden(m.id,true)}>Masquer</button></div></div>})}{hiddenMeetings.length>0&&<details style={{marginTop:14}}><summary><b>Réunions masquées ({hiddenMeetings.length})</b></summary>{hiddenMeetings.map(m=><div className="aiacHistoryRow" key={m.id}><div><b>{m.title}</b><small>{format(m.starts_at)}</small></div><button className="aiacAgendaPrimary" disabled={busy===`hide-${m.id}`} onClick={()=>void toggleHidden(m.id,false)}>Réafficher</button></div>)}</details>}</div>
 </section>;
}
