"use client";

import { ChangeEvent,useMemo,useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Props={profileId:string;meetingId?:string;analysisId?:string;bodyId?:string|null;projectId?:string|null;onDone?:()=>void;label?:string};
async function digest(file:File){const buffer=await file.arrayBuffer();return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',buffer))).map(v=>v.toString(16).padStart(2,'0')).join('');}
export default function MultiDocumentUploader({profileId,meetingId,analysisId,bodyId,projectId,onDone,label='Joindre plusieurs documents'}:Props){const supabase=useMemo(()=>createClient(),[]);const[files,setFiles]=useState<File[]>([]);const[busy,setBusy]=useState(false);const[notice,setNotice]=useState('');function choose(e:ChangeEvent<HTMLInputElement>){setFiles(Array.from(e.target.files||[]));}async function upload(){if(!files.length)return;setBusy(true);setNotice('');let done=0;for(const file of files){try{if(file.size>15*1024*1024)throw new Error(`${file.name} dépasse 15 Mo.`);const safe=file.name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9._-]/g,'-');const path=`${profileId}/${crypto.randomUUID()}-${safe}`;const up=await supabase.storage.from('aiac-documents').upload(path,file,{contentType:file.type,upsert:false});if(up.error)throw up.error;const{data:doc,error}=await supabase.from('documents').insert({owner_id:profileId,title:file.name,file_url:path,file_name:file.name,mime_type:file.type||null,size_bytes:file.size,visibility:'explicit',classification:'internal',body_id:bodyId||null,project_id:projectId||null,document_status:'approved'}).select('id').single();if(error||!doc){await supabase.storage.from('aiac-documents').remove([path]);throw error||new Error('Document non enregistré');}const{error:ve}=await supabase.from('document_versions').insert({document_id:doc.id,version_number:1,storage_path:path,file_name:file.name,mime_type:file.type||null,size_bytes:file.size,checksum_sha256:await digest(file),change_note:'Version initiale',created_by:profileId});if(ve)throw ve;if(meetingId){const{error:le}=await supabase.from('meeting_documents').insert({meeting_id:meetingId,document_id:doc.id,shared_by:profileId});if(le)throw le;const{data:people}=await supabase.from('meeting_participants').select('user_id').eq('meeting_id',meetingId);const grants=(people||[]).filter((p:any)=>p.user_id!==profileId).map((p:any)=>({document_id:doc.id,user_id:p.user_id,can_download:true,can_upload_version:false,can_manage:false,reason:'Document partagé avec les participants de la réunion',granted_by:profileId}));if(grants.length)await supabase.from('document_access_grants').upsert(grants,{onConflict:'document_id,user_id'});}if(analysisId){const{error:ge}=await supabase.from('gender_analysis_documents').insert({analysis_id:analysisId,document_id:doc.id,linked_by:profileId});if(ge)throw ge;}done++;}catch(e){setNotice(e instanceof Error?e.message:'Échec de chargement');break;}}setBusy(false);if(done===files.length){setNotice(`${done} document(s) chargé(s) et partagé(s).`);setFiles([]);onDone?.();}}
return <div className="pwInset"><label className="wide"><b>{label}</b><input type="file" multiple onChange={choose} disabled={busy}/></label>{files.length>0&&<><p>{files.length} fichier(s) sélectionné(s)</p><ul>{files.map(f=><li key={`${f.name}-${f.size}`}>{f.name} · {(f.size/1024).toFixed(0)} Ko</li>)}</ul><button type="button" onClick={()=>void upload()} disabled={busy}>{busy?'Chargement…':'Charger et partager'}</button></>}{notice&&<p className="pwWarning">{notice}</p>}</div>}
