"use client";

import { useEffect,useMemo,useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Notification={id:string;title:string;body:string;href:string|null;read_at:string|null;created_at:string;category:string};
export function MyPositionNotifications(){const supabase=useMemo(()=>createClient(),[]);const[rows,setRows]=useState<Notification[]>([]);const[q,setQ]=useState("");const[loading,setLoading]=useState(true);async function load(){const{data}=await supabase.from('notifications').select('id,title,body,href,read_at,created_at,category').order('created_at',{ascending:false}).limit(150);setRows((data||[]) as Notification[]);setLoading(false);}useEffect(()=>{void load();const ch=supabase.channel('my-position-notifications-fast').on('postgres_changes',{event:'*',schema:'public',table:'notifications'},()=>void load()).subscribe();return()=>{void supabase.removeChannel(ch);};},[]);async function mark(id:string){await supabase.from('notifications').update({read_at:new Date().toISOString()}).eq('id',id);setRows(x=>x.map(r=>r.id===id?{...r,read_at:new Date().toISOString()}:r));}const filtered=rows.filter(r=>`${r.title} ${r.body} ${r.category}`.toLowerCase().includes(q.toLowerCase()));return <section className="portalPanel"><div className="pwToolbar"><div><h2>Notifications du poste</h2><p>Vue légère : elle charge uniquement vos alertes, sans recharger tout le portail.</p></div><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Rechercher une notification…"/></div>{loading?<p>Chargement…</p>:filtered.length?filtered.map(r=><article className="pwAdminRow" key={r.id}><div><b>{r.title}</b>{!r.read_at&&<span className="pwTag">Non lue</span>}<p>{r.body}</p><small>{new Date(r.created_at).toLocaleString('fr-FR')}</small><div className="pwButtons">{!r.read_at&&<button onClick={()=>void mark(r.id)}>Marquer lue</button>}{r.href&&<a href={r.href}>Ouvrir</a>}</div></div></article>):<p>Aucune notification.</p>}</section>}

type Audit={id:string;actor_id:string|null;action:string;entity_type:string;entity_id:string|null;details:any;created_at:string};
export function MyPositionAudit(){const supabase=useMemo(()=>createClient(),[]);const[rows,setRows]=useState<Audit[]>([]);const[q,setQ]=useState("");const[loading,setLoading]=useState(true);useEffect(()=>{void(async()=>{const{data}=await supabase.from('audit_logs').select('id,actor_id,action,entity_type,entity_id,details,created_at').order('created_at',{ascending:false}).limit(250);setRows((data||[]) as Audit[]);setLoading(false);})();},[]);const filtered=rows.filter(r=>`${r.action} ${r.entity_type} ${JSON.stringify(r.details||{})}`.toLowerCase().includes(q.toLowerCase()));return <section className="portalPanel"><div className="pwToolbar"><div><h2>Audit rapide</h2><p>250 événements récents. Le centre d’audit complet reste disponible au besoin.</p></div><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Action, objet, détail…"/></div>{loading?<p>Chargement…</p>:<div className="pwScroll"><table><thead><tr><th>Date</th><th>Action</th><th>Objet</th><th>Détails</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td>{new Date(r.created_at).toLocaleString('fr-FR')}</td><td>{r.action}</td><td>{r.entity_type}</td><td><small>{JSON.stringify(r.details||{}).slice(0,500)}</small></td></tr>)}</tbody></table></div>}</section>}
