"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type CapabilityCatalog={capability_key:string;label:string;description:string;risk_level:string};
type PositionCapability={key:string;scope_mode:string;label?:string;risk_level?:string};
type PositionRow={position_id:string;code:string;title:string;institutional_level:string;body_id:string|null;body_code:string|null;body_name:string|null;authority_scope:string|null;is_statutory:boolean;status:string;decision_reference:string|null;reports_to_position_id:string|null;role_key:string|null;role_family:string|null;job_purpose:string|null;responsibilities:string[];workspace_modules:string[];source_basis:string|null;source_status:string;sensitive_access_level:string;slot_count:number;assignment_count:number;capabilities:PositionCapability[]};

const scopes=[
  ["assignment","Affectation"],["body","Organe"],["project","Projet"],["subordinates","Subordonnés"],["institution","Institution"],
] as const;

function lines(v:string){return v.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);}

export default function PositionReferenceAdmin(){
 const supabase=useMemo(()=>createClient(),[]);
 const [rows,setRows]=useState<PositionRow[]>([]),[catalog,setCatalog]=useState<CapabilityCatalog[]>([]);
 const [query,setQuery]=useState(""),[capQuery,setCapQuery]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
 async function load(){setLoading(true);const [r,c]=await Promise.all([supabase.rpc("position_reference_catalog_admin",{search_text:null,max_rows:2000}),supabase.from("position_capability_catalog").select("capability_key,label,description,risk_level").order("capability_key")]);if(r.error||c.error)setNotice(r.error?.message||c.error?.message||"Chargement impossible");else{setRows((r.data||[]) as PositionRow[]);setCatalog((c.data||[]) as CapabilityCatalog[]);}setLoading(false);}
 useEffect(()=>{void load();},[]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return rows.filter(r=>!q||`${r.code} ${r.title} ${r.role_key||""} ${r.role_family||""} ${r.body_code||""} ${r.body_name||""} ${r.status}`.toLowerCase().includes(q));},[rows,query]);
 if(loading)return <section className="portalPanel"><h2>Référentiel des fiches de poste</h2><p>Chargement du référentiel…</p></section>;
 return <section className="portalPanel"><div className="pwToolbar"><div><h2>Référentiel des fiches de poste — super-administration</h2><p>Modifier la définition d’un poste sans confondre la fiche de fonction avec la personne qui l’occupe. Les changements sont audités.</p></div><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher code, poste, famille, organe…"/></div>{notice&&<div className="pwNotice" role="status">{notice}</div>}<p className="pwTag">{filtered.length} fiche(s)</p><div className="pwAdminRows">{filtered.slice(0,300).map(r=><PositionEditor key={r.position_id} row={r} catalog={catalog} capQuery={capQuery} setCapQuery={setCapQuery} busy={busy} setBusy={setBusy} setNotice={setNotice} reload={load} supabase={supabase}/>)}</div>{filtered.length>300&&<p className="pwWarning">300 fiches affichées. Affinez la recherche.</p>}</section>;
}

function PositionEditor({row,catalog,capQuery,setCapQuery,busy,setBusy,setNotice,reload,supabase}:{row:PositionRow;catalog:CapabilityCatalog[];capQuery:string;setCapQuery:(v:string)=>void;busy:boolean;setBusy:(v:boolean)=>void;setNotice:(v:string)=>void;reload:()=>Promise<void>;supabase:any}){
 const [caps,setCaps]=useState<Record<string,string>>(()=>Object.fromEntries((row.capabilities||[]).map(c=>[c.key,c.scope_mode])));
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setNotice("");const f=new FormData(e.currentTarget);const {error}=await supabase.rpc("update_position_definition_admin",{target_id:row.position_id,target_title:String(f.get("title")||"").trim(),target_job_purpose:String(f.get("job_purpose")||"").trim()||null,target_responsibilities:lines(String(f.get("responsibilities")||"")),target_workspace_modules:lines(String(f.get("workspace_modules")||"")),target_authority_scope:String(f.get("authority_scope")||"").trim(),target_decision_reference:String(f.get("decision_reference")||"").trim(),target_source_basis:String(f.get("source_basis")||"").trim(),target_source_status:String(f.get("source_status")||"").trim(),target_sensitive_access_level:String(f.get("sensitive_access_level")||"").trim(),target_status:String(f.get("status")||"")});if(error)setNotice(error.message);else{setNotice(`Fiche ${row.code} mise à jour et auditée.`);await reload();}setBusy(false);}
 async function saveCaps(){setBusy(true);setNotice("");const payload=Object.entries(caps).map(([key,scope_mode])=>({key,scope_mode}));const {error}=await supabase.rpc("set_position_capabilities_admin",{target_position_id:row.position_id,target_capabilities:payload});if(error)setNotice(error.message);else{setNotice(`Habilitations de ${row.code} mises à jour.`);await reload();}setBusy(false);}
 async function remove(){const reason=window.prompt(`Motif de suppression définitive de la fiche ${row.code} :`);if(!reason)return;if(!window.confirm(`Supprimer définitivement la fiche ${row.code} ? Le serveur refusera si elle est déjà référencée.`))return;setBusy(true);setNotice("");const {error}=await supabase.rpc("delete_position_definition_admin",{target_id:row.position_id,target_reason:reason});if(error)setNotice(error.message);else{setNotice(`Fiche ${row.code} supprimée définitivement.`);await reload();}setBusy(false);}
 const q=capQuery.trim().toLowerCase();const visibleCaps=catalog.filter(c=>!q||`${c.capability_key} ${c.label} ${c.description}`.toLowerCase().includes(q));
 return <details className="pwAdminRow"><summary><span><b>{row.code}</b> · {row.title}{row.body_code?` · ${row.body_code}`:""}</span><span className="pwTag">{row.status} · {row.slot_count} poste(s) établi(s) · {row.assignment_count} affectation(s)</span></summary><div className="pwDetail"><form className="pwForm" onSubmit={save}><label className="wide">Intitulé<input name="title" defaultValue={row.title} required minLength={2}/></label><label className="wide">Finalité du poste<textarea name="job_purpose" defaultValue={row.job_purpose||""}/></label><label className="wide">Responsabilités — une par ligne<textarea name="responsibilities" defaultValue={(row.responsibilities||[]).join("\n")}/></label><label className="wide">Modules/outils — un par ligne<textarea name="workspace_modules" defaultValue={(row.workspace_modules||[]).join("\n")}/></label><label>Portée d’autorité<input name="authority_scope" defaultValue={row.authority_scope||""}/></label><label>Décision / référence<input name="decision_reference" defaultValue={row.decision_reference||""}/></label><label className="wide">Base documentaire<input name="source_basis" defaultValue={row.source_basis||""}/></label><label>Statut de la source<input name="source_status" defaultValue={row.source_status||"operational_reference"}/></label><label>Niveau d’accès sensible<input name="sensitive_access_level" defaultValue={row.sensitive_access_level||"none"}/></label><label>État<select name="status" defaultValue={row.status}><option value="draft">Brouillon</option><option value="active">Actif</option><option value="suspended">Suspendu</option><option value="abolished">Aboli</option></select></label><button disabled={busy}>Enregistrer la fiche</button></form><div className="pwNested"><h4>Habilitations du poste</h4><p>Une habilitation cochée donne le droit selon sa portée. Le super-admin reste transversal uniquement sous MFA AAL2.</p><input value={capQuery} onChange={e=>setCapQuery(e.target.value)} placeholder="Rechercher une habilitation…"/><div className="pwCaps">{visibleCaps.map(c=>{const checked=Object.prototype.hasOwnProperty.call(caps,c.capability_key);return <article key={c.capability_key}><label className="check"><input type="checkbox" checked={checked} onChange={e=>setCaps(cur=>{const next={...cur};if(e.target.checked)next[c.capability_key]="assignment";else delete next[c.capability_key];return next;})}/> <b>{c.label}</b></label><small>{c.capability_key} · risque {c.risk_level}</small><p>{c.description}</p>{checked&&<select value={caps[c.capability_key]} onChange={e=>setCaps(cur=>({...cur,[c.capability_key]:e.target.value}))}>{scopes.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>}</article>})}</div><div className="pwButtons"><button type="button" onClick={()=>void saveCaps()} disabled={busy}>Enregistrer les habilitations</button><button type="button" className="danger" onClick={()=>void remove()} disabled={busy}>Supprimer définitivement la fiche</button></div></div></div></details>;
}
