-- Indexes de couverture des clés étrangères ajoutées au point 4.
create index if not exists account_reviews_body_idx on public.account_reviews(body_id);
create index if not exists account_reviews_position_idx on public.account_reviews(position_assignment_id);
create index if not exists account_reviews_reviewer_idx on public.account_reviews(reviewer_id,created_at desc);
create index if not exists conversation_members_added_by_idx on public.conversation_members(added_by);
create index if not exists conversations_archived_by_idx on public.conversations(archived_by);
create index if not exists conversations_assigned_to_idx on public.conversations(assigned_to,status,updated_at desc);
create index if not exists conversations_org_unit_idx on public.conversations(organization_unit_id,status);
create index if not exists document_access_grants_granted_by_idx on public.document_access_grants(granted_by);
create index if not exists document_access_logs_user_idx on public.document_access_logs(user_id,created_at desc);
create index if not exists document_access_logs_version_idx on public.document_access_logs(version_id);
create index if not exists document_approvals_document_idx on public.document_approvals(document_id,status,requested_at desc);
create index if not exists document_approvals_requested_by_idx on public.document_approvals(requested_by,requested_at desc);
create index if not exists document_folders_body_idx on public.document_folders(body_id);
create index if not exists document_folders_case_idx on public.document_folders(case_id);
create index if not exists document_folders_created_by_idx on public.document_folders(created_by);
create index if not exists document_folders_project_idx on public.document_folders(project_id);
create index if not exists document_versions_created_by_idx on public.document_versions(created_by,created_at desc);
create index if not exists documents_activity_idx on public.documents(activity_id);
create index if not exists documents_archived_by_idx on public.documents(archived_by);
create index if not exists documents_beneficiary_idx on public.documents(beneficiary_id);
create index if not exists documents_body_idx on public.documents(body_id,classification);
create index if not exists documents_case_idx on public.documents(case_id);
create index if not exists documents_conversation_idx on public.documents(conversation_id,created_at desc);
create index if not exists documents_folder_idx on public.documents(folder_id,updated_at desc);
create index if not exists documents_member_idx on public.documents(member_id);
create index if not exists documents_partner_idx on public.documents(partner_id);
create index if not exists governance_bodies_reporting_idx on public.governance_bodies(reporting_body_id);
create index if not exists message_attachments_attached_by_idx on public.message_attachments(attached_by);
create index if not exists message_attachments_document_idx on public.message_attachments(document_id);
create index if not exists position_assignments_appointed_by_idx on public.position_assignments(appointed_by);
create index if not exists position_assignments_member_idx on public.position_assignments(member_id,status);
create index if not exists position_assignments_supervisor_idx on public.position_assignments(supervisor_assignment_id);
create index if not exists position_definitions_body_idx on public.position_definitions(body_id,status);
create index if not exists position_definitions_created_by_idx on public.position_definitions(created_by);
create index if not exists position_definitions_reports_to_idx on public.position_definitions(reports_to_position_id);
create index if not exists profiles_validated_by_idx on public.profiles(validated_by);
